### ISSUE TITLE
記事や書籍、Podcastのリンク追加

### ISSUE THREAD

**Issue by kenzo-tanaka** [Katsukiniwa/awesome-software-design-ja#2]
個人的に広まって欲しい記事や書籍、Podcastがいくつかあるので、まとめてみました！
(趣旨にずれているものがありましたらすいません🙇‍)

### オブジェクト指向

SOLID原則をRubyコードで解説されている本です。
[オブジェクト指向設計実践ガイド ~Rubyでわかる 進化しつづける柔軟なアプリケーションの育て方 | Sandi Metz, 髙山 泰基 |本 | 通販 | Amazon](https://www.amazon.co.jp/%E3%82%AA%E3%83%96%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E6%8C%87%E5%90%91%E8%A8%AD%E8%A8%88%E5%AE%9F%E8%B7%B5%E3%82%AC%E3%82%A4%E3%83%89-Ruby%E3%81%A7%E3%82%8F%E3%81%8B%E3%82%8B-%E9%80%B2%E5%8C%96%E3%81%97%E3%81%A4%E3%81%A5%E3%81%91%E3%82%8B%E6%9F%94%E8%BB%9F%E3%81%AA%E3%82%A2%E3%83%97%E3%83%AA%E3%82%B1%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%81%AE%E8%82%B2%E3%81%A6%E6%96%B9-Sandi-Metz/dp/477418361X)

### システム設計

Railsを中心に設計に関する話題が多めのPodcastです。
[texta.fm • A podcast on Anchor](https://anchor.fm/textafm/)

### モデリング

「出来事」をモデリングする設計に関して説明されている記事、書籍、Podcastです。

- https://scrapbox.io/kawasima/イミュータブルデータモデル
- [楽々ERDレッスン (CodeZine BOOKS) | (株)スターロジック 羽生 章洋 |本 | 通販 | Amazon](https://www.amazon.co.jp/%E6%A5%BD%E3%80%85ERD%E3%83%AC%E3%83%83%E3%82%B9%E3%83%B3-CodeZine-BOOKS-%E3%82%B9%E3%82%BF%E3%83%BC%E3%83%AD%E3%82%B8%E3%83%83%E3%82%AF-%E7%BE%BD%E7%94%9F/dp/4798110663/ref=sr_1_1?__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&keywords=%E6%A5%BD%E3%80%85ERD&qid=1636864441&sr=8-1)
- [3. Low-Code Development by texta.fm](https://anchor.fm/textafm/episodes/3--Low-Code-Development-emr6k3)
- [27. 論理削除とは何か？どのような解法があるのか？ w/ twada | fukabori.fm](https://fukabori.fm/episode/27)

### デザインパターン

今は項目としてデザインパターンはなかったですが、今後追加する予定でしたら、以下のPodcastがとても良かったので共有しておきます。

* [48. GoFデザインパターンとDI (前編) w/ twada | fukabori.fm](https://fukabori.fm/episode/48)
* [49. GoFデザインパターンとDI + リファクタリング (後編) w/ twada | fukabori.fm](https://fukabori.fm/episode/49)

**Comment by Katsukiniwa** [comment]
反応滞ってしまって申し訳ありません。
メッツ本、texts.fm良いと思います！
こちらプルリク作成して頂いてよろしいでしょうか？

**Comment by kenzo-tanaka** [comment]
PR出しましたー！
